name: Quantum-ai

on:
  schedule:
    - cron: "50 0 * * *"
  pull_request:
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out theis repo
      - uses: actions/checkout@v2
      # Start a Slack workflow using a webhook trigger
      # https://github.com/slackapi/slack-github-action
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r ./requirements/requirements-quantum-ai.txt
      - name: Run Quantum Computer
        run: |
          huggingface-cli login
          python ./app/quantum-ai.py
        env:
          DIFFUSION_TOKEN: ${{ secrets.DIFFUSION_TOKEN }}
          IBMQ_TOKEN: ${{ secrets.IBMQ_TOKEN }}
          STABILITY_KEY: ${{ secrets.STABILITY_KEY }}
